CREATE SEQUENCE supermarket_seq
INCREMENT BY 1
START WITH 0
MAXVALUE 10
NOCYCLE;

CREATE TABLE SUPERMARKETS(
    SUPERMARKET_ID NUMBER(2) DEFAULT supermarket_seq.NEXTVAL NOT NULL,
    SUPERMARKET_NAME CHAR(20),
    NUMBER_OF_PRODUCTS NUMBER(4),
    CONSTRAINT supermarkets_pk PRIMARY KEY(SUPERMARKET_ID)
);

CREATE SEQUENCE category_seq
INCREMENT BY 2
START WITH 2
MAXVALUE 100
NOCYCLE;

CREATE TABLE CATEGORIES(
    CATEGORY_ID NUMBER(3) DEFAULT category_seq.NEXTVAL NOT NULL,
    CATEGORY_NAME CHAR(20),
    NUM_OF_PRODUCTS NUMBER(4),
    CONSTRAINT categories_pk PRIMARY KEY(CATEGORY_ID)
);

CREATE SEQUENCE product_seq
INCREMENT BY 3
START WITH 1000
MAXVALUE 2003
NOCYCLE;

CREATE TABLE PRODUCTS(
    PRODUCT_ID NUMBER(4) NOT NULL,
    PRODUCT_NAME CHAR(20),
    PRICE NUMBER(4,2),
    PROMOTION_START_DATE DATE,
    PROMOTION_END_DATE DATE,
    SUPERMARKET_ID NUMBER(2) DEFAULT supermarket_seq.NEXTVAL NOT NULL,
    CATEGORY_ID NUMBER(3) DEFAULT category_seq.NEXTVAL NOT NULL,
    CONSTRAINT products_pk PRIMARY KEY(PRODUCT_ID_ID),
    CONSTRAINT supermarkets_fk FOREIGN KEY(SUPERMARKET_ID)
        REFERENCES SUPERMARKETS(SUPERMARKET_ID) ON DELETE CASCADE,
    CONSTRAINT categories_fk FOREIGN KEY(CATEGORY_ID)
        REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE
);